<?php

namespace App\Modules\Catalog\Infrastructure\Persistence\Database\Seeders;

use App\Modules\Catalog\Infrastructure\Persistence\Eloquent\Models\Category;
use App\Shared\Laravel\Infrastructure\Persistence\Eloquent\Models\Translation;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Ramsey\Uuid\Uuid;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $root = [
            [
                'id' => $verbsId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'verbs',
                'type' => 'grammar',
                'color' => '#E1F5EE',
                'icon' => '⚡️',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $verbsId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Глаголы',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $verbsId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Verbs',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $nounsId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'nouns',
                'type' => 'grammar',
                'color' => '#E6F1FB',
                'icon' => '📦',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $nounsId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Существительные',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $nounsId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Nouns',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $adjectivesId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'adjectives',
                'type' => 'grammar',
                'color' => '#EEEDFE',
                'icon' => '🎨',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $adjectivesId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Прилагательные',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $adjectivesId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Adjectives',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $adverbsId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'adverbs',
                'type' => 'grammar',
                'color' => '#EEEDFE',
                'icon' => '🎨',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $adverbsId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Наречия',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $adverbsId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Adverbs',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $prepositionId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'preposition',
                'type' => 'grammar',
                'color' => '#FBEAF0',
                'icon' => '🛫',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $prepositionId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Предлоги',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $prepositionId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Preposition',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $conjunctionId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'conjunction',
                'type' => 'grammar',
                'color' => '#FBEAF0',
                'icon' => '🛫',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $conjunctionId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Союзы',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $conjunctionId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Conjunction',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $phrasalId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'phrasal_verbs',
                'type' => 'special',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $phrasalId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Фразовые глаголы',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $phrasalId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Phrasal Verbs',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $actionProcessId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'action_process',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $actionProcessId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Действие и процесс',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $actionProcessId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Action and process',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $stageActionPartWholeId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'stage_action_part_whole',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $stageActionPartWholeId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Этапы действия и части целого',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $stageActionPartWholeId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Stages of action and parts of a whole',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $physicalActionGeneralId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'physical_action_general',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $physicalActionGeneralId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Физические действия (общие)',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $physicalActionGeneralId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Physical actions (general)',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $humanPhysicalActionId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'human_physical_action',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanPhysicalActionId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Физические действия человека',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $physicalActionGeneralId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Human physical actions',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $movementSpaceId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'movement_space',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $movementSpaceId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Движение и пространство',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $movementSpaceId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Movement and space',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $movementId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'movement',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $movementId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Движение',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $movementId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Movement',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $spaceId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'space',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $spaceId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Пространство',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $spaceId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Space',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $spaceNatureId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'space_nature',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $spaceNatureId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Пространство и природа',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $spaceNatureId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Space and nature',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $spacesId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'spaces',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $spacesId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Места',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $spacesId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Spaces',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $availabilityAffilOperationId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'availability_affiliation_operation',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $availabilityAffilOperationId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Наличие, принадлежность и работа',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $availabilityAffilOperationId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Availability, affiliation and operation',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $presenceAbsenceBelongingId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'presence_absence_belonging',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $presenceAbsenceBelongingId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Наличие, отсутствие и принадлежность',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $presenceAbsenceBelongingId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Presence, absence and belonging',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $workCooperationId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'work_cooperation',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $workCooperationId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Работа и сотрудничество',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $workCooperationId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Work and cooperation',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $cooperationId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'cooperation',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $cooperationId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Сотрудничество',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $cooperationId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Cooperation',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $workCareerId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'work_career',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $workCareerId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Работа и карьера',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $workCareerId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Work and career',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $professionPositionId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'profession_position',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $professionPositionId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Профессии и должности',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $professionPositionId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Professions and positions',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $thinkingFeelingCommId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'thinking_feeling_comm',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $thinkingFeelingCommId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Мышление, чувства и общение',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $thinkingFeelingCommId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Thinking, feeling and communication',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $communicationId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'communication',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $communicationId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Общение',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $communicationId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Communication',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $thinkingId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'thinking',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $thinkingId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Мышление',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $thinkingId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Thinking',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $psychologyFeelingId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'psychology_feeling',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $psychologyFeelingId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Психология и чувства',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $psychologyFeelingId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Psychology and feelings',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $struggleLawArmyId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'struggle_law_army',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $struggleLawArmyId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Борьба, закон и армия',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $struggleLawArmyId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Struggle, law and army',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $struggleId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'struggle',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $struggleId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Борьба',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $struggleId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Struggle',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $lawId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'law',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $lawId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Закон',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $lawId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Law',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $armyId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'army',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $armyId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Армия',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $armyId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Army',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $economyBusinessId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'economy_business',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $economyBusinessId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Экономика и бизнес',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $economyBusinessId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Economy and business',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $industryId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'industry',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $industryId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Промышленность',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $industryId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Industry',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $moneyQuantityId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'money_quantity',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $moneyQuantityId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Деньги и количество',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $moneyQuantityId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Money and quantity',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $humanId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'human',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Человек',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Human',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $humanLifeId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'human_life',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanLifeId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Жизнь человека',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanLifeId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Human life',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $humanPersonalityId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'human_personality',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanPersonalityId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Личность человека',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanPersonalityId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Human personality',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $humanAnatomyId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'human_anatomy',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanAnatomyId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Анатомия человека',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $humanAnatomyId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Human anatomy',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $homeEverydayLifeEnterId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'home_everyday_life',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $homeEverydayLifeEnterId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Дом, быт и развлечения',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $homeEverydayLifeEnterId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Home, everyday life and entertainment',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $homeEverydayLifeId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'home_everyday_life',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $homeEverydayLifeId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Дом и быт',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $homeEverydayLifeId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Home and everyday life',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $natureWorldId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'nature_world',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $natureWorldId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Природа и мир',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $natureWorldId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Nature and world',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $animalPlantId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'animal_plant',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $animalPlantId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Животные и растения',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $animalPlantId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Animals and plants',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $physicalPhenomenaId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'physical_phenomena',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $physicalPhenomenaId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Физические явления',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $physicalPhenomenaId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Physical phenomena',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $materialId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'material',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $materialId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Материалы',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $materialId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Materials',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $timeId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'time',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $timeId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Время',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $timeId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Time',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $mathLogicScienceId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'math_logic_science',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $mathLogicScienceId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Математика, логика и наука',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $mathLogicScienceId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Mathematics, logic and science',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $mathematicsId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'mathematics',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $mathematicsId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Математика',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $mathematicsId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Mathematics',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $logicId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'logic',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $logicId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Логика',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $logicId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Logic',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $scienceArtId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'science_art',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $scienceArtId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Наука и искусство',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $scienceArtId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Science and art',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $techEngineId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'tech_engine',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $techEngineId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Техника и технология',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $techEngineId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Technology and engineering',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $techniqueId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'technique',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $techniqueId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Техника',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $techniqueId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Technique',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $transportId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'transport',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $transportId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Транспорт',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $transportId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Transport',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $infoTechId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'info_tech',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $infoTechId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Информационные технологии',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $infoTechId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Information technology',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $artCultureId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'art_culture',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $artCultureId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Искусство и культура',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $artCultureId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Arts and culture',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $paintingPhotoId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'painting_photo',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $paintingPhotoId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Живопись и фотография',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $paintingPhotoId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Painting and photography',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $cinemaTheatreMusicId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'cinema_theatre_music',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $cinemaTheatreMusicId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Кино, театр и музыка',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $cinemaTheatreMusicId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Cinema, theatre and music',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $literatureId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'literature',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $literatureId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Литература',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $literatureId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Literature',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $religionId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'religion',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $religionId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Религия',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $religionId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Religion',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $sportId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'sport',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $sportId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Спорт',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $sportId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Sport',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $studyEducationId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'study_education',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $studyEducationId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Учёба и образование',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $studyEducationId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Study and education',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $studyId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'study',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $studyId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Учёба',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $studyId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Study',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $societyStateId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'society_state',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $societyStateId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Общество и государство',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $societyStateId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Society and the state',
                    ],
                ],
                'created_at' => now(),
            ],
            // new category
            [
                'id' => $familyRelationId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'family_relation',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $familyRelationId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Семья и отношения',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $familyRelationId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Family and relationships',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $familyId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'family',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $familyId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Семья',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $familyId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Family',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $relationshipsId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'relationships',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $relationshipsId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Взаимоотношения',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $relationshipsId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Relationships',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $foodId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'food',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $foodId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Еда',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $foodId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Food',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $clothId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'cloth',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $clothId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Одежда',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $clothId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Cloth',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $medicineId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'medicine',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $medicineId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Медицина',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $medicineId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Medicine',
                    ],
                ],
                'created_at' => now(),
            ],
            //
            [
                'id' => $moralityBehaviorId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'morality_behavior',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $moralityBehaviorId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Мораль и поведение',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $moralityBehaviorId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Morality and behavior',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $diversityId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'diversity',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $diversityId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Разнообразие',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $diversityId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Diversity',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $difEasyOrdUnuId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'dif_easy_ord_unu',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $difEasyOrdUnuId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Тредный и лёгкий, обычный и необычный',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $difEasyOrdUnuId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Difficult and easy, ordinary and unusual',
                    ],
                ],
                'created_at' => now(),
            ],
            //
            [
                'id' => $feelingLogicId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'feeling_logic',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $feelingLogicId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Ощущения и логика',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $feelingLogicId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Feelings and logic',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $qualityId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'quality',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $qualityId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Качество',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $qualityId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Quality',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $sizeShapeId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'size_shape',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $sizeShapeId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Размер и форма',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $sizeShapeId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Size and shape',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $physicalQualityId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'physical_quality',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $physicalQualityId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Физические качества',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $physicalQualityId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Physical qualities',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $importanceProbabilityId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'importance_probability',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $importanceProbabilityId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Важность и вероятность',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $importanceProbabilityId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Importance and probability',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $colorId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'color',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $colorId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Цвета',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $colorId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Colors',
                    ],
                ],
                'created_at' => now(),
            ],
            //
            [
                'id' => $adverbMannerId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'adverb_manner',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $adverbMannerId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Образ действия',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $adverbMannerId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Adverb of manner',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $quantityId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'quantity',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $quantityId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Количество',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $quantityId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Quantity',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $measureDegreesId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'measure_degrees',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $measureDegreesId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Меры и степени',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $measureDegreesId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Measures and degrees',
                    ],
                ],
                'created_at' => now(),
            ],
            [
                'id' => $introConnectingWordId = Uuid::uuid4()->toString(),
                'parent_id' => null,
                'slug' => 'intro_connecting_word',
                'type' => 'theme',
                'color' => '#EAF3DE',
                'icon' => '🔗',
                'translations' => [
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $introConnectingWordId,
                        'locale' => 'ru',
                        'field' => 'name',
                        'value' => 'Вводные и соединительные слова',
                    ],
                    [
                        'id' => Uuid::uuid4()->toString(),
                        'entity_type' => Category::class,
                        'entity_id' => $introConnectingWordId,
                        'locale' => 'en',
                        'field' => 'name',
                        'value' => 'Introductory and connecting words',
                    ],
                ],
                'created_at' => now(),
            ],
        ];

        $categories = array_map(
            fn (array $item) => Arr::except($item, ['translations']),
            $root
        );

        Category::query()->insert($categories);

        $translations = array_merge(
            ...array_map(
                fn (array $item) => $item['translations'],
                $root
            )
        );

        Translation::query()->insert($translations);
    }
}
